### PR TITLE
Feature/ DIOS-6969 MultiChannel for 2.0

### PR DESCRIPTION
**Pull request by mupatt-dolby**
Multi-channel work for Stream monitor work. Left legacy code unchanged but moved. New code could almost replace the existing code.

To improve

- stats viewer is not implemented
- remove legacy code
- Layer selection isn't working

### CODE REVIEW

**Comment by mshaa92** [comment]
Great LGFM, Clean and structured well 👍  , here are just few notes.

- Regarding StreamingContainerViewModel, shall isLive/Live badge be per every video (StreamingScreen) instead of the whole container? 
- I think Select quality layer should be per each video view as well as every stream can have different quality layers ?
- In order to apply quality selection we have to put enableAsync for track in a method and add for this play action a field for layer to be passed to enableAsync. But as u said it is not implemented yet.  
- Need to put connect() method within try catch because in order of this call failure coroutine cancellation is not caught causing app crash. Try using coroutine safeLaunch extension method better for this case. 
- I got a crash when i disconnect wifi then connect my wifi again on TV emulator

**Comment by mupatt-dolby** [comment]
Good question about whether the live badge and stream quality should be a per stream thing or a shared component. I personally think it would be too cluttered to have it on each stream. I'm open to adjusting that. The live badge would be easier to do that for than the stream quality selection. @RameshDPrasad do you have thoughts?

* For applying the stream quality selection should be applied to each
  * the options are Auto, High, Medium, Low
  * if a player only had 1 quality it wouldn't switch
  * if a player only had 2 qualities, then I would consider Medium and Low to be the same quality (rounding down)

**Comment by mupatt-dolby** [comment]
Good callout on try catch for connect, I've added that

**Comment by mupatt-dolby** [comment]
I get a crash on my TV emulator when trying to connect in general. Adding the try/catch around connect fixed the crash and showed each stream as unavailable.

**Review by RameshDPrasad — APPROVED** [review]

**Pull request merged**
